### ISSUE TITLE
Bug in name mangling of (un)nested procedures

### ISSUE THREAD

**Issue by tenko** [zaskar9/oberon-lang#36] opened 2024-04-09 21:58 UTC
Consider the following code:

```oberon
MODULE Test;

PROCEDURE Run1();
VAR   
    str : ARRAY 25 OF CHAR;
    PROCEDURE Assert(b: BOOLEAN);
    BEGIN
        ASSERT(b)
    END Assert;
BEGIN
    str := "test1";
END Run1;

PROCEDURE Run2();
VAR   
    str : ARRAY 25 OF CHAR;
    PROCEDURE Assert(b: BOOLEAN);
    BEGIN
        ASSERT(b)
    END Assert;
BEGIN
    str := "test2";
END Run2;

BEGIN
    Run1();
    Run2()
END Test.
```

This fails to compile with the following error:

> Test.ob07:17:5: error: Function Test__Assert already defined.

**Comment by zaskar9** [comment] 2024-04-10 05:08
This one is easy to diagnose! Nested procedures are implemented in `oberon-lang` by unnesting them. This is the job of class `LambdaLifter`. The problem is that line [112](https://github.com/zaskar9/oberon-lang/blob/542ab09d056524c98178415f715701c76ff5f239/src/analyzer/LambdaLifter.cpp#L112) of that class assigns both nested `Assert` procedures the same name. This can be easily fixed by including the full "nested path" in the new name of the unnested procedure.

**Comment by tenko** [comment] 2024-04-10 06:11
Excellent. I will have a look at it.

**Closed** 2024-04-10 15:46 UTC
Labels: bug
